name: build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: package

      - name: Upload production bundle
        uses: actions/upload-artifact@v4
        with:
          path: './omnivox-datadisplay-0.1.0-alpha.1.tgz'
          name: 'omnivox-datadisplay-0.1.0-alpha.1.tgz'
